
service: curso-sls-express

custom:
  tableName: 'users-table-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true
      port: 8000
      inMemory: true
    stages:
      - dev
    #migration:
    #  dir: offline/migrations

plugins:
  - serverless-dynamodb-local
  # https://www.npmjs.com/package/serverless-dotenv-plugin
  - serverless-dotenv-plugin
  - serverless-offline
  
provider:
  name: aws
  runtime: nodejs10.x
  profile: serverless
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn"] }
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: handler.generic
    events:
      - http: ANY /
      - http: ANY {proxy+}
resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}

