service: api-keys # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  profile: curso-sls
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  
  # The next line will create the new key into API Gateway and it will setted in the specified file.
  apiKeys:
    - ${file(./config.${self:provider.stage}.json):API_KEY}

functions:
  hello:
    handler: handler.hello
    events:
    - http:
        path: /
        method: get
        private: true
